on: push
env:
  SCI_DIR: datasci
jobs:
  wave:
    name: ripple
    runs-on: ubuntu-latest
    steps:
    - name: Check-out datasci repository
      uses: actions/checkout@v2
      with:
        repository: master/datasci
        path: ${{ env.SCI_DIR }}
        run: perl ${{ env.SCI_DIR }}/mk_UIb.pl
