name: action0
on: [push]
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          perl test.pl
          git add my_test.txt
          git commit -m "updating file"
          git push
