on: push
env:
  SCI_DIR: datasci
jobs:
  wave:
    name: ripple
    runs-on: ubuntu-latest
    steps:
    - name: Check-out datasci repository
      uses: actions/checkout@v2
      with:
        repository: master/datasci
        path: ${{ env.SCI_DIR }}
        run: |
      git config --global user.email "resident.parkewood@gmail.com"
      git config --global user.name "Ge Wang"
      perl ${{ env.SCI_DIR }}/mk_UIh.pl
      git add kelly.txt
      git commit -m "updating file"
      git push
